CS3733-D21-Team-B/CS3733-D21-Team-B-BWApp

- src/main/java/edu/wpi/cs3733/D21/teamB/database/DatabaseHandler.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/ETAPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapDrawer.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapEditorPopupManager.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/data/Node.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/AddNodePopupController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/EditNodePopupController.java
- src/test/java/edu/wpi/cs3733/D21/teamB/MapTests.java
You can now drag and drop nodes in map editing mode
Edges will follow them
It is accurately reflected in the database
Can't drag them past 0 or max width/height
updated database create table for nodes to make sure they can't be more than the max value
Add/edit node popups can't be more than max X or Y for coords now
> Drag nodes

- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
search bar for treeview does not find intermediate nodes anymore (HALL or WALK)
> search bar does not find intermediate nodes anymore (HALL or WALK)

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapDrawer.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
1. cleaned up the node coloring spaghetti in pathFindingMenuController
2. little bit of cleanup with path drawing in MapDrawer
> Pathfinding mini-refactor

- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/pathfindingMenu.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/editUserMenu.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/userInformationDatabase.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/requestForms/religiousRequestForm.fxml
> Moving buttons again

- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
made a helper function that alphabetizes a list of tree nodes and then called it where necessary.
Did not alphabatize favorites so they can organize that how they want
> alphebetize tree nodes 

- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/ServiceRequestDatabaseController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/loginPage.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/registerPage.fxml
highlights requests in the database until someone is assigned to them
> Highlight unassigned requests

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapDrawer.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
1. When you click on the floor indicator on the path it brings you to the indicated floor
> Floor switches when you click on the floor indicator

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapDrawer.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/TxtDirPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/misc/edge.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/pathfindingMenu.fxml
Stops are now brown (reflected in the key)
Normal path is half translucent
> Map UI improvement

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/data/DelEdgeBtwnFloorsWindow.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/node/DelEdgeBtwnFloorsAYSWindow.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/node/NodeMenuPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/DelEdgeBtwnFloorsAYSController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/DelEdgeBtwnFloorsController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/NodePopupWindowController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/delEdgeBtwnFloorsAYSWindow.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/delEdgeBtwnFloorsWindow.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/nodePopupWindow.fxml
Can delete edges between floors.
1. Click on a node in the map editor
2. Click on the "Delete edge between floors" button
3. Choose the long name of the node that we want to delete an edge to
4. Click the delete button
5. Click yes on the "Are you sure?" prompt
> Can now delete edges between floors

- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/DefaultServiceRequestFormController.java
> sort location dropdowns in request forms into alphabetical order

- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
pathfinding based on covid status. if dangerous, adds emergency stop.
> pathfinding based on covid survey status

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/node/AddNodePopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/AddNodePopupController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/addNodePopup.fxml
> Add node popup now has a a color picker

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapPathPopupManager.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/data/GraphicalInputData.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/node/GraphicalInputPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/node/NodeInfoWindow.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/node/NodeMenuPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/misc/ChangeParkingSpotController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/misc/GraphicalInputController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/EditNodePopupController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/NodeInfoWindowController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/NodePopupWindowController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/misc/graphicalInput.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/nodeInfoWindow.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/nodePopupWindow.fxml
There is an info button when clicking on a node in the map editor
> Add info window to node menu popup

- src/main/java/edu/wpi/cs3733/D21/teamB/database/DatabaseHandler.java
- src/main/java/edu/wpi/cs3733/D21/teamB/database/RequestMutator.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/requests/CaseManagerRequest.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/requests/LanguageRequest.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/requests/SocialWorkerRequest.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/CaseManagerRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/FloralDeliveryRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/GiftRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/LanguageRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/ReligiousRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/SocialWorkerRequestFormController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/requestForms/caseManagerRequestForm.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/requestForms/languageRequestForm.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/requestForms/socialWorkerRequestForm.fxml
Fixed the following:
- floral delivery must be current date or later
- floral delivery start/end time
- religious request must be current date or later
- religious request start/end time
- gift request must be current date or later
- gift request start/end time
- language interpreter add date of arrival and make sure it's the current date or later
- social worker add date of arrival and make sure it's the current date or later
- case manager add date of arrival and make sure it's the current date or later
> Request validations

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/ETAPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapDrawer.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/requestForms/languageRequestForm.fxml
Visual update to keep the eta popup off the path as much as possible
> Bug fixes general

- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/SecurityRequestFormController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/requestForms/securityRequestForm.fxml
Assigning someone to security is a combo box instead of typing something in
> Assign security

- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/serviceRequestMenu.fxml
Reverts CS3733-D21-Team-B/CS3733-D21-Team-B-BWApp#203
> Revert "Service menu"

- src/main/java/edu/wpi/cs3733/D21/teamB/views/BasePageController.java
Doesn't play the first focused node and then focuses on the stack pane so that nothing plays until you start tabbing
> Emergency doesn't immediately start talking on every page

- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/RegisterPageController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/loginPage.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/registerPage.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/pathfindingMenu.fxml
Moved the key to the suggested location on pathfinding, increased contrast of login elements
> Andrew's UI notes

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/node/AlignNodePopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/AlignNodePopupController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/nodePopup/alignNodePopup.fxml
In the alignment popup, there's a radio button set that can select the type of alignment (best fit as before, horizontal, vertical)
> nodes can now align horizontally or vertically

- src/main/java/edu/wpi/cs3733/D21/teamB/App.java
- src/main/java/edu/wpi/cs3733/D21/teamB/database/DatabaseHandler.java
- src/main/java/edu/wpi/cs3733/D21/teamB/database/UserMutator.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/User.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/BasePageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/RegisterPageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/EditUserController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/SettingsMenuController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/UserDirectoryMenuController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/UserInformationDatabaseController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/registerPage.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/editUserMenu.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/userDirectoryMenu.fxml
> Per user tts

- src/main/java/edu/wpi/cs3733/D21/teamB/database/DatabaseHandler.java
- src/main/java/edu/wpi/cs3733/D21/teamB/database/UserMutator.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/HelpDialog.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/SceneSwitcher.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/UserWrapper.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/BasePageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/ChangePasswordController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/EditUserController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/ServiceRequestDatabaseController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/ServiceRequestMenuController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/SettingsMenuController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/UserInformationDatabaseController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/DefaultServiceRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/ExternalTransportationRequestFormController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/changePassword.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/editUserMenu.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/settingsMenu.fxml
Refactored help dialog
Added to settings page "edit profile" and "change password" which do those things which includes TTS
> User edit profile page

- src/main/java/edu/wpi/cs3733/D21/teamB/App.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/ExternalCommunication.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/RequestWrapper.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/UserWrapper.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/covidSurvey/CovidSurveyController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/RegisterPageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/CovidRequestFormController.java
- src/test/java/edu/wpi/cs3733/D21/teamB/DatabaseHandlerTest.java
Email uses multithreading now and is also static because it didn't need to be an object
> Email now uses multithreading so it doesn't lag out so much

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapCache.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapDrawer.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapPathPopupManager.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/TxtDirPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/data/TxtDirPopupData.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
The gesture pane zooms and scrolls so the path is entirely in view with some padding on both sides. Additionally, in text directions, the part of the path that is highlighted is centered as well.
> Center path

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/TxtDirPopup.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/ExternalCommunication.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/misc/TxtDirPopupController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/map/misc/showTextDir.fxml
Logged in users can email themselves text directions in the text directions popup
> Email text directions

- src/main/java/edu/wpi/cs3733/D21/teamB/database/DatabaseHandler.java
- src/main/java/edu/wpi/cs3733/D21/teamB/database/RequestMutator.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/requests/CovidSurveyRequest.java
- src/main/java/edu/wpi/cs3733/D21/teamB/entities/requests/Request.java
- src/main/java/edu/wpi/cs3733/D21/teamB/util/RequestWrapper.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/covidSurvey/CovidSurveyController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/covidSurvey/CovidSurveyNurseCheckController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/ServiceRequestDatabaseController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/CovidRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/SanitationRequestFormController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/covidSurvey/covidSurvey.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/covidSurvey/covidSurveyNurseCheck.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/serviceRequestDatabase.fxml
A nurse can now accept or deny a patient and record it in the database
Once a covid survey is submitted the admin marks the user either safe or dangerous like normal using the edit button. The request is then marked as in progress. When the patient enters the hospital the nurse (any staff) can see the in progress request in the service request database and by using the edit button can record whether they were admitted or not.
The admission is recorded in a new column in the CovidSurveyRequests table called admitted.
> Nurse check ins

- src/main/java/edu/wpi/cs3733/D21/teamB/entities/map/MapDrawer.java
nodes on the path that indicate up and down movements are now colored properly
> fixed bug with coloring up and down nodes

- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/LoginPageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/RegisterPageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/CaseManagerRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/EmergencyFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/ExternalTransportationRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/FloralDeliveryRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/FoodDeliveryRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/GiftRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/InternalTransportationRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/LanguageRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/MedDeliveryRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/ReligiousRequestFormController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/requestForms/SocialWorkerRequestFormController.java
When you click on the login or register button the cursor will immediately go to the user name text box.
Same for service requests that have patient names as the first field.
> Focus requested on text boxes

- src/main/resources/edu/wpi/cs3733/D21/teamB/views/misc/aboutPage.fxml
Reformatted the about page to be in a gridpane
> About page

- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/LoginPageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/RegisterPageController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/loginPage.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/registerPage.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/menus/settingsMenu.fxml
TTS works for all fields in login now but we don't want it on Emergency so I left that out
> Credits TTS

- src/main/java/edu/wpi/cs3733/D21/teamB/views/BasePageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/RegisterPageController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/loginPage.fxml
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/registerPage.fxml
The register TTS is fixed, we had to remove the scroll pane to make it work. The login TTS was also slightly modified since the emergency and exit button did not have accessibility text
> Fix Register TTS (and log in)

- src/main/java/edu/wpi/cs3733/D21/teamB/views/face/Camera.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/LoginPageController.java
- src/main/resources/edu/wpi/cs3733/D21/teamB/views/login/loginPage.fxml
black square shows up when you toggle face id in login page
> black square shows up when you toggle face id in login page

- src/main/java/edu/wpi/cs3733/D21/teamB/views/covidSurvey/CovidFormAcceptedController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/covidSurvey/CovidFormPendingController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/covidSurvey/CovidSurveyController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/login/MainPageController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/map/PathfindingMenuController.java
- src/main/java/edu/wpi/cs3733/D21/teamB/views/menus/UserDirectoryMenuController.java
covid survey scene switching fix
> covid survey scene switching fix
